### PR TITLE
Fix onboarding tests and customer data wp-cli commands

### PR DESCRIPTION
**Pull request by arunshenoy99**
## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by wpscholar** [comment]
@arunshenoy99 Can you address the merge conflicts on this, please? The tests should run for you once those are resolved.

**Comment by arunshenoy99** [comment]
> @arunshenoy99 Can you address the merge conflicts on this, please? The tests should run for you once those are resolved.

Done, those branding changes look really relevant now, thanks @wpscholar for that, don't see any test runs on this branch but a cypress test did run on one of our forked branches (https://github.com/officiallygod/bluehost-wordpress-plugin/actions/runs/3005236796) but this seems to be failing on cannot import `db.sql`.

**Comment by arunshenoy99** [comment]
@wpscholar one more thing I noticed when I removed the database import and ran the workflow(https://github.com/officiallygod/bluehost-wordpress-plugin/actions/runs/3005551177) all of our tests are failing because of the `notifications` and `settings` API's returning 404's can this be because of permalinks not being setup? 
Exit to WordPress -- Exit to WordPress Page -- after all hook (failed)
Basic Info Page -- Check if Drawer opened -- before all hook (failed)
The `Syntax error unexpected token < in JSON` seems to be originating from the 404's

**Comment by wpscholar** [comment]
@arunshenoy99 Yes, we need to make sure all our API calls don't assume that pretty permalinks are in use. We should update those to use this format: `/index.php?rest_route=newfold-ecommerce/v1/plugins/status`.

It's strange that the Cypress test run couldn't import that DB file since I can see it in your branch. 

We probably need to re-add the "synchronize" PR trigger for tests to run when your branch updates.

**Comment by wpscholar** [comment]
@arunshenoy99 Let's get the conflicts handled on this PR and run the tests to see if we can get them to pass.

**Comment by arunshenoy99** [comment]
> @arunshenoy99 Let's get the conflicts handled on this PR and run the tests to see if we can get them to pass.

Ack @wpscholar, these tests are outdated now, the team is working on updating and new tests in the fork: https://github.com/officiallygod/bluehost-wordpress-plugin/pulls, we'll create a new PR, can we close this one?

**Comment by wpscholar** [comment]
@arunshenoy99 Closing this out now.

**Pull request closed without merging**
