### PR TITLE
Ecommerce version bump to 1.3.35

### PR DESCRIPTION
**Pull request by aratidgr8**
## Proposed changes

**Bug Fix:**

- [PRESS4-547](https://jira.newfold.com/browse/PRESS4-547) | Launch your site button should only display when in coming soon mode. When clicked and the site is no longer in coming soon mode, it should be removed from the screen. Clicking the launch button should also update the site status in the admin bar.
- [PRESS0-1625](https://jira.newfold.com/browse/PRESS0-1625) | P3 incident on 26th June fixed by @aratidgr8 in https://github.com/newfold-labs/wp-module-ecommerce/pull/333

**Tech Debt:**

- [GitHub Issue](https://github.com/newfold-labs/wp-module-ecommerce/issues/331) : Updated the DB variable name fromshowMigrationStep tonfd_show_migration_step as per NewFold coding standards.
- Cypress tests improvised - Implemented the testIsolation flag so each test is expected to be more independent, and combined tests that were not independent to run in the same it

**Feature Requests:**

- PRESS0-631 | Dismiss woo notice

## Type of Change

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by wpscholar** [comment]
@aratidgr8  Can you address the current conflicts, please? Thank!

**Comment by aratidgr8** [comment]
@wpscholar Conflicts have been resolved. Please help me with review. Thanks.

**Comment by circlecube** [comment]
It looks like all the workflows are failing. From the workflows I see the following:

# Lock file errors
- The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.

**Review by wpalani — APPROVED** [review]

**Comment by circlecube** [comment]
Thanks @aratidgr8

**Pull request merged**
