### PR TITLE
Update to Cypress 10

### PR DESCRIPTION
**Pull request by wpscholar**
## Proposed changes

Update to Cypress 10

## Type of Change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Comment by wpscholar** [comment]
@circlecube This PR is strictly updating us to Cypress 10 and Node 16. One test still fails, but we have another issue created for that.

**Comment by wpscholar** [comment]
Oh, this also resolves #149

**Comment by wpscholar** [comment]
I am mentioning this also resolves #150 so these will auto-resolve once the code is merged.

**Comment by circlecube** [comment]
Looks good. The interface feels so much more modern too!

**Review by circlecube — APPROVED** [review]

**Pull request merged**
