### PR TITLE
move onboarding cypress test

### PR DESCRIPTION
**Pull request by circlecube**
## Proposed changes

I fixed the merge conflicts in the other PR in dev and merged it. This PR moves the cypress test file so it can run. Still not seeing the test pass though.

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by circlecube** [comment]
This does at least give us a build file for testing before we get the release branch going.

**Comment by arunshenoy99** [comment]
@circlecube @wpscholar I dug a bit into this today to figure out why this was happening only for the tests turns out customer data was the culprit,

1. Our WP_Crons come alive only on Ecommerce plans to perform the installs.
2. We determine whether the customer purchased an Ecommerce plan based on the data returned by https://github.com/bluehost/bluehost-wp-customer-data/blob/67a308dbef35ce6646c872faf3b967ef3a23c624/includes/Customer.php#L63
3. We used to simulate customer data for the tests using https://github.com/bluehost/bluehost-wordpress-plugin/blob/eef1875bf4860d700b4f2c3f87ded7fd67948379/tests/cypress/support/commands.js#L87
4. Seems like there was an update in the customer collect data logic because of which `bh_cdata` contains
Screenshot 2023-01-09 at 11 44 33 AM
because of which the WP_Crons never come to life.

Now I am not sure how we can solve this problem since no matter what I set in `bh_cdata` or `bh_cdata_guapi` including the addition of `customer_id` it resorts back to the screenshot state probably cause it cannot connect to Hiive.

**Comment by circlecube** [comment]
@arunshenoy99 I think this may be the problem. The module lines you reference are outdated. We added another check to make sure the customer data includes a customer_id as well. See the latest version of the module: https://github.com/bluehost/bluehost-wp-customer-data/blob/main/includes/Customer.php#L155

It would be good to note that this release is also using the new customer data module - the code is nearly unchanged, but the reference for this build would be here: https://github.com/newfold-labs/wp-module-customer-bluehost/blob/trunk/includes/CustomerBluehost.php#L127

**Comment by arunshenoy99** [comment]
> @arunshenoy99 I think this may be the problem. The module lines you reference are outdated. We added another check to make sure the customer data includes a customer_id as well. See the latest version of the module: https://github.com/bluehost/bluehost-wp-customer-data/blob/main/includes/Customer.php#L155
> 
> It would be good to note that this release is also using the new customer data module - the code is nearly unchanged, but the reference for this build would be here: https://github.com/newfold-labs/wp-module-customer-bluehost/blob/trunk/includes/CustomerBluehost.php#L127

Thanks for letting me know about the new module, but even this one goes same as the old code from `collect` -> `refresh_data` -> `get_account_info` -> `connect` which retrieves the data from `bh_cdata_guapi` -> `$info['customer_id']  = AccessToken::get_user();` overrides `customer_id` causing subsequent collect calls to place a call to Hiive returning `Access Denied`

**Comment by arunshenoy99** [comment]
**Update:** I was finally able to set the customer data in [this](https://github.com/bluehost/bluehost-wordpress-plugin/commit/4f6cb39e03bf457dac963083c0ee89fe7de7e555) commit and I verified this works by visiting onboarding without the `flow=ecommerce` param (the module was not disabled) also the WP_Cron schedules show up now meaning they have been registered(another sign customer data is working), but it seems like we have run into another blockade here 😞 WP_Crons don't seem to work well in `wp-env` because I waited for about 20 mins and they never ran even though they were scheduled every 30 and 10 seconds, when I installed `WP_Crontrol` and took a look this is what I found
Screenshot 2023-01-10 at 11 34 49 AM
Looks like there is some kind of a connectivity issue when the cron scheduler tried to make calls to itself in the `wp-env` environment causing the cron to never run.

On clicking "Learn More": https://github.com/johnbillion/wp-crontrol/wiki/Problems-with-spawning-a-call-to-the-WP-Cron-system#curl-error-7-failed-to-connect-connection-refused
Known issue with `wp-env`: https://github.com/WordPress/gutenberg/issues/20569#issuecomment-689203786

**Comment by circlecube** [comment]
Closing since a better branch was merged already.

**Pull request closed without merging**
