### PR TITLE
Adding Sales Channel route under Store main menu item

### PR DESCRIPTION
**Pull request by aratidgr8**
## Proposed changes

JIRA: https://jira.newfold.com/browse/PRESS0-1480

- To improve the visibility of the EcomDash plugin to our Ecommerce plus customers.
- If a customer has the Ecomdash entitlement, then the customer should see the Ecomdash landing page from the Store navigation under "Sales Channels".
- When a customer clicks on the page the first time, the CTA Get Started, it should open a new window with the Ecomdash onboarding.
- After a customer has setup the Ecomdash plugin, the customer should see the landing page with Open Dashboard as the CTA instead of the Get Started CTA.
- Related Ecommerce module [PR](https://github.com/newfold-labs/wp-module-ecommerce/pull/335)
- [Figma](https://www.figma.com/design/eKHvqb3T4Idairwe5TF29a/PRESS0-993-Ecomdash-Brand-Plugin-Integration?node-id=65-5155&t=JMlfLNHDNWphsmrm-1)

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by wpalani — APPROVED** [review]
Looks good. There's a minor linting problem, do you mind addressing it before merging?

**Comment by wpalani** [comment]
> Looks good. There's a minor linting problem, do you mind addressing it before merging?

@aratidgr8 Checking if you had a chance to fix the lint issue?

**Comment by aratidgr8** [comment]
@wpalani  sorry not sure how I missed on [this](https://github.com/bluehost/bluehost-wordpress-plugin/pull/1169#issuecomment-2223692069) comment.  Apologies, will fix it ASAP.

**Comment by aratidgr8** [comment]
@wpalani Lint fixes are done. 
@wpscholar  there is a related [PR](https://github.com/newfold-labs/wp-module-ecommerce/pull/335) in Ecommerce module for which QA & code review signoff are pending. Request you to not to merge this PR in 17th July release.
Thanks!

**Comment by wpalani** [comment]
> @wpalani Lint fixes are done. @wpscholar there is a related [PR](https://github.com/newfold-labs/wp-module-ecommerce/pull/335) in Ecommerce module for which QA & code review signoff are pending. Request you to not to merge this PR in 17th July release. Thanks!

@aratidgr8 
I see that [your other PR in the e-commerce module](https://github.com/newfold-labs/wp-module-ecommerce/pull/335) is still open. Pushing this to the July 31 milestone.

**Comment by chrisdavidmiles** [comment]
pre-login

**Comment by chrisdavidmiles** [comment]
post-login

**Pull request merged**
