### PR TITLE
PRESS0-2212: Import WP Solutions Banner on Home page

### PR DESCRIPTION
**Pull request by aratidgr8**
## Proposed changes

JIRA: https://jira.newfold.com/browse/PRESS0-2212
Import WP Solutions Banner Component on Home page.
Refer to [PR](https://github.com/newfold-labs/wp-module-ecommerce/pull/350)  for more details.

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by diwanshuster — APPROVED** [review]

**Comment by wpscholar** [comment]
Running full test matrix now that the code conflicts have been resolved: https://github.com/bluehost/bluehost-wordpress-plugin/actions/runs/10925458847

**Comment by wpscholar** [comment]
@aratidgr8 Let's look into why so many tests are failing.

**Comment by aratidgr8** [comment]
@wpscholar  we are checking why tests are failing will keep you posted on updates. Thanks!

**Comment by krsomayagi** [comment]
The tests are failing because the ecommerce package is still on an older version, and the solutions banner import does not exist.

**Comment by aratidgr8** [comment]
> @aratidgr8 Let's look into why so many tests are failing: https://github.com/bluehost/bluehost-wordpress-plugin/actions/runs/10925458847

@wpscholar As confirmed by @krsomayagi in [comment](https://github.com/bluehost/bluehost-wordpress-plugin/pull/1307#issuecomment-2378590378) tests will pass once home page banner [PR](https://github.com/newfold-labs/wp-module-ecommerce/pull/350) is merged. Please confirm in that case are we good to merge this PR then?

**Comment by wpscholar** [comment]
@aratidgr8  Yes, let's merge both of those

**Review by circlecube — APPROVED** [review]

**Pull request merged**
