### PR TITLE
Update onboarding module to 1.11.2

### PR DESCRIPTION
**Pull request by circlecube**
## Proposed changes

This updates the onboarding module from 1.10.4 to 1.11.2. Lots of changes which can be found here: https://github.com/newfold-labs/wp-module-onboarding/compare/1.10.4...1.11.2

I'm looking for cypress tests to pass before merging.

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by circlecube** [comment]
It looks like we need to coordinate the `wp-module-onboarding-data` versions. The onboarding module requires `0.3.0` and the e-commerce module requires `0.2.0`. I believe we'll need to tag a new release of e-commerce to bump the `wp-module-onboarding-data`? I'm not familiar with the differences in the two versions though and I hope they are compatible.

**Comment by circlecube** [comment]
Composer messages:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires newfold-labs/wp-module-ecommerce ^1.3.0 -> satisfiable by newfold-labs/wp-module-ecommerce[v1.3.0].
    - You can only install one version of a package, so only one of these can be installed: newfold-labs/wp-module-onboarding-data[0.0.2, 0.0.3].
    - newfold-labs/wp-module-onboarding 1.11.2 requires newfold-labs/wp-module-onboarding-data ^0.0.3 -> satisfiable by newfold-labs/wp-module-onboarding-data[0.0.3].
    - newfold-labs/wp-module-ecommerce v1.3.0 requires newfold-labs/wp-module-onboarding-data ^0.0.2 -> satisfiable by newfold-labs/wp-module-onboarding-data[0.0.2].
    - Root composer.json requires newfold-labs/wp-module-onboarding ^1.11.2 -> satisfiable by newfold-labs/wp-module-onboarding[1.11.2].

**Comment by circlecube** [comment]
Also, as noted in #714 we're looking for details in the PR and recording(s).

**Comment by circlecube** [comment]
I've pulled in the updated 1.3.1 e-commerce module to fix the composer dependency mismatch.

**Review by wpalani — APPROVED** [review]

**Pull request merged**
