### PR TITLE
Update code standards, add misc dev files, make linting more good-er

### PR DESCRIPTION
**Pull request by bradp**
huh

## Changes

Brad Parbs is a code standards nerd and I like to automate as many things as possible.

- Adds `.editorconfig` to consisten-ize things (_docs: [PHPStorm EditorConfig plugin](https://www.jetbrains.com/help/phpstorm/editorconfig.html) [VS Code extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)_)
- Updates `package.json` with some new goodies
  - Adds `lint:php` and `lint:php:fix` that call the composer scripts
  - Adds `lint` and `lint:fix` that will run all the different linting scripts (JS, php, etc) concurrently
  - Adds `i18n` and `test` commands that will also run all the relevant `<command>:<subcommand>` scripts
- Adds `jsconfig.json` to allow IDE eslint to correctly associate aliases 
- Fixes imports in `package.json` to directly pull in dependencies rather than relying on transient dependencies
- Introduces [PHP CS Fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer) to lint and automatically fix some things that phpcs isn't great at.
- 
## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate) TODO @bradp add info to README.md or create a CONTRIBUTING.md file to outline the standards

## Further comments

Standards fixes and linting changes for the code base are being handled in #852 to keep the diff clearer here.

### CODE REVIEW

**Comment by circlecube** [comment]
@bradp - I'd love to get this merged, do you have time to resolve the conflicts?

**Comment by bradp** [comment]
@circlecube I should have time later this week to do it! 🎉

**Comment by bradp** [comment]
For ease of review, #1009 is only the added code standards file, while this PR is that plus fixed files.

**Comment by circlecube** [comment]
Based on the lack of updates on this and the now number of conflicts, I think we can close this and reopen or restart if we have the need in the future.

**Pull request closed without merging**
