### PR TITLE
add list to action

### PR DESCRIPTION
**Pull request by ryanjduffy**
Debugging Replay on top of #175

### CODE REVIEW

**Comment by ryanjduffy** [comment]
@wpscholar - Mind approving workflows for me? Hoping to track down why we're not able to upload replays! :)

**Comment by wpscholar** [comment]
@ryanjduffy Sorry, a bit slow responding, but it has been enabled.

**Comment by wpscholar** [comment]
@ryanjduffy Hmm... why would we be getting the "github oauth token for github.com contains invalid characters" message for an external contributor, but not an internal contributor?

**Comment by wpscholar** [comment]
May need to check on Composer version: https://nono.ma/github-oauth-token-for-github-com-contains-invalid-characters-on-composer-install

**Pull request merged**
