### PR TITLE
Implement Facebook Connect in Settings Page

### PR DESCRIPTION
**Pull request by arunshenoy99**
## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Created this for: https://github.com/bluehost/bluehost-wordpress-plugin/pull/1019 so that tests run.

### CODE REVIEW

**Comment by wpscholar** [comment]
@arunshenoy99 Can you give this PR a refresh?

**Comment by wpscholar** [comment]
@ramyakrishnai The changes look good. Let's resolve the issue with the `composer.lock` file and fix the linting errors.

**Comment by ramyakrishnai** [comment]
> @ramyakrishnai The changes look good. Let's resolve the issue with the `composer.lock` file and fix the linting errors.

Updated @wpscholar

**Comment by manikantakailasa** [comment]
> @arunshenoy99 / @ramyakrishnai / @manikantakailasa - Shouldn't this file live in the Facebook module? src/app/pages/settings/socialMediaAccounts.js

The Facebook module will only provide access to or receive data from Facebook. According to the plans, we may have more social media connections in the future, including Instagram. so this file will help to connect to different social media modules.

**Review by wpscholar — APPROVED** [review]

**Comment by wpscholar** [comment]
@manikantakailasa Please update to address conflicts. Thanks!

**Comment by wpscholar** [comment]
@ramyakrishnai It appears this still has a conflict

**Review by wpscholar — APPROVED** [review]

**Pull request merged**
