### PR TITLE
feature/Launchpad with view & add buttons - PRESS4 509

### PR DESCRIPTION
**Pull request by ramyakrishnai**
## Proposed changes

We will have a pages menu item
And there will be launchpads for each public content type
And there will be lanchpads for each public custom content type
And there will be a "view all" option for each type
And there will be an "add new" option for each type.

story - https://jira.newfold.com/browse/PRESS4-509

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Created this for: https://github.com/bluehost/bluehost-wordpress-plugin/pull/1023 so that tests run.

### CODE REVIEW

**Comment by wpscholar** [comment]
Posting previous feedback from @wpalani in order to preserve context here:

> Thanks, @manikantakailasa, for opening this PR. Here are some items I noticed while reviewing the code/UI:
> 
> * There appears to be an extra border or shadow around some of the UI boxes that are throwing off the UI.
>   ext-border
> * UI needs a mobile breakpoint similar to other pages in the app. Please look at other pages/components to see how the responsiveness is handled.
> * Products box needs to check if WooCommerce is active before displaying it. Now, the links on it go to an invalid post type page when clicked on while WooCommerce is not present.
> * Booking and Appointments box needs to check if WooCommerce is active in addition to the Yith plugin before displaying it. Now, the links on it go to an invalid post type page when clicked on while WooCommerce is not present.
> * `pagesAndPosts/index.js` has `/* eslint-disable prettier/prettier */` comment on top which disables eslint/prettier this needs to be removed and the component needs to be linted properly.
> * Reslove outstanding merge conflicts.
> * Please write Cypress tests for the new page/UI.
> * Less important: the root `package.json` file spacing appears to be changed from tabs/4 to spaces/2. Please fix for consistency.

**Comment by wpscholar** [comment]
@ramyakrishnai It looks like tests didn't run with the last commit. Any ideas why?

**Comment by wpscholar** [comment]
@wpalani Would you be able to do another review to see if your concerns were addressed?

**Comment by ramyakrishnai** [comment]
> @ramyakrishnai It looks like tests didn't run with the last commit. Any ideas why?

@wpscholar  I'm unsure why it didn't occur the previous time, but after editing it, it began.

**Review by wpalani — APPROVED** [review]

**Pull request merged**
