### PR TITLE
Ecommerce version bump 1.3.33

### PR DESCRIPTION
**Pull request by aratidgr8**
## Proposed changes

- `PRESS0-1325` : Post Migration scripts by @krsomayagi in https://github.com/newfold-labs/wp-module-ecommerce/pull/307
- `PRESS0-1159` : Update Store Home Page by @aratidgr8 @manikantakailasa in https://github.com/newfold-labs/wp-module-ecommerce/pull/308
- `PRESS0-1448`: Remove Unused Thumbnail Service Code by @arunshenoy99 in https://github.com/newfold-labs/wp-module-ecommerce/pull/315
- Ecommerce version bump 1.3.32 by @aratidgr8 in https://github.com/newfold-labs/wp-module-ecommerce/pull/326
- PRESS0-1497 | Fix sitecapability and store page test failures in plugin workflow by @sangeetha-nayak in #322
- eCommerce version bump 1.3.33 by @ramyakrishnai in #327
## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by circlecube** [comment]
Looks like these latest e-commerce module releases (1.3.32 and 1.3.33) do not have passing cypress tests. I see there are more tests being skipped and still failing tests not being skipped. Ideally we do not skip tests but can update them to pass. This is the only way to ensure code integrity and functional products for users.

Passing tests is a requirement for tagging a module release.

**Comment by aratidgr8** [comment]
@sangeetha-nayak  Can you please take a look at failed cypress tests?

**Comment by ramyakrishnai** [comment]
Hi @circlecube , the latest ecommerce version 1.3.33 has been released to fix all the ecommerce related tests, In the current PR, the tests that are failing are from other modules, coming soon and deactivation module. We skipped a test that is wondercart related as that is breaking because of console errors coming from features module. So, we skipped it for now until it is fixed.

**Comment by circlecube** [comment]
Branches should follow the naming convention so that workflows will trigger tests to run. See https://newfold-labs.github.io/how-we-work/9-version-control.html#branch-naming and  https://github.com/bluehost/bluehost-wordpress-plugin/blob/main/.github/workflows/cypress.yml#L6-L15

**Comment by circlecube** [comment]
Since we have a conflict and branch name didn't trigger tests, I've set a new PR up at #1128. Closing this one.

**Pull request closed without merging**
