### PR TITLE
Show Active Products in Brand Plugin

### PR DESCRIPTION
**Pull request by girish-lokapure**
## Proposed changes

The scope of this PR includes:

-  Creation of a "My Products" section on the home page in brand plugin that lists out products. 
-  A/B test "abTestShowMyProducts" set to zero percent so we can turn it on for a few people and get feedback

image

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [x] Linting and tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by wpalani** [comment]
Module for this feature has not yet been released. Pushing this to the July 24th milestone.

**Comment by chrisdavidmiles** [comment]
Can you push it out another week? There's more things that need to be addressed before this is ready.
- Let's not make it a top level nav, just put it on the homepage underneath everything else.
- Make it an A/B test set to zero percent so we can turn it on for a few people and get feedback.

**Comment by wpalani** [comment]
> Can you push it out another week? There's more things that need to be addressed before this is ready.
> 
> * Let's not make it a top level nav, just put it on the homepage underneath everything else.
> * Make it an A/B test set to zero percent so we can turn it on for a few people and get feedback.

Pushed to July 31 milestone.

**Comment by girish-lokapure** [comment]
> Can you push it out another week? There's more things that need to be addressed before this is ready.
> 
> * Let's not make it a top level nav, just put it on the homepage underneath everything else.
> * Make it an A/B test set to zero percent so we can turn it on for a few people and get feedback.

I have implemented the changes, please check the screenshot attached

**Comment by wpalani** [comment]
I did some testing and this doesn't seem to be working. I added a comment detailing the issue here: https://jira.newfold.com/browse/PRESS0-719?focusedCommentId=14721912&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14721912

Pushing this to August 14 milestone.

**Comment by girish-lokapure** [comment]
> I did some testing and this doesn't seem to be working. I added a comment detailing the issue here: https://jira.newfold.com/browse/PRESS0-719?focusedCommentId=14721912&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14721912
> 
> Pushing this to August 14 milestone.

Seems like the env variables are missing and needs to be added to vapor
FULFILLMENT_GATEWAY_API =""
FULFILLMENT_GATEWAY_SYSTEM_ID = ""
FULFILLMENT_GATEWAY_SECRET = ""

**Comment by wpalani** [comment]
This PR is currently blocked by https://jira.newfold.com/browse/PRESS1-423

**Comment by chrisdavidmiles** [comment]
Is this ready to go into the Aug 28 release?

**Comment by wpalani** [comment]
> Is this ready to go into the Aug 28 release?

That's the plan, doing some testing on it today.

**Review by wpalani — APPROVED** [review]

**Pull request merged**
